#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${1:-"$ROOT_DIR/tmp/llm-access-cloud-bundle-test"}"

rm -rf "$OUT_DIR"
"$ROOT_DIR/scripts/render_llm_access_cloud_bundle.sh" "$OUT_DIR"

assert_absent() {
  local pattern="$1"
  local file="$2"
  if grep -F -- "$pattern" "$file" >/dev/null; then
    printf 'unexpected pattern in %s: %s\n' "$file" "$pattern" >&2
    return 1
  fi
}

test -s "$OUT_DIR/llm-access.service"
test -s "$OUT_DIR/llm-access-usage-worker.service"
test -s "$OUT_DIR/mnt-llm\\x2daccess.mount"
test -s "$OUT_DIR/juicefs-llm-access-usage.service"
test -s "$OUT_DIR/juicefs-llm-access.resource-guard.conf"
test -s "$OUT_DIR/staticflow-wait-llm-access-state"
test -s "$OUT_DIR/Caddyfile"

grep -F 'ExecStart=/usr/bin/bash -lc' "$OUT_DIR/llm-access.service"
grep -F "ExecStartPre=/usr/bin/bash -lc 'set -a; . /mnt/llm-access/config/neon.env; exec /usr/local/bin/staticflow-wait-llm-access-state api'" "$OUT_DIR/llm-access.service"
grep -F "ExecStart=/usr/bin/bash -lc 'set -a; . /mnt/llm-access/config/neon.env; exec /usr/local/bin/llm-access serve --bind \"\$LLM_ACCESS_BIND_ADDR\" --state-root \"\$LLM_ACCESS_STATE_ROOT\" --postgres-control-database-url-env LLM_ACCESS_CONTROL_DATABASE_URL --usage-journal-dir \"\$LLM_ACCESS_USAGE_JOURNAL_DIR\" --request-cache-url-env LLM_ACCESS_REQUEST_CACHE_URL --request-cache-key-prefix llma'" "$OUT_DIR/llm-access.service"
grep -F -- '--postgres-control-database-url-env LLM_ACCESS_CONTROL_DATABASE_URL' "$OUT_DIR/llm-access.service"
grep -F -- 'usage-journal-dir "$LLM_ACCESS_USAGE_JOURNAL_DIR"' "$OUT_DIR/llm-access.service"
grep -F -- '--request-cache-url-env LLM_ACCESS_REQUEST_CACHE_URL' "$OUT_DIR/llm-access.service"
grep -F -- '--request-cache-key-prefix llma' "$OUT_DIR/llm-access.service"
grep -F 'Environment=mimalloc_allow_thp=0' "$OUT_DIR/llm-access.service"
grep -F 'Environment=mimalloc_disallow_arena_alloc=1' "$OUT_DIR/llm-access.service"
grep -F 'Environment=mimalloc_purge_delay=0' "$OUT_DIR/llm-access.service"
assert_absent 'Environment=LLM_ACCESS_BACKGROUND_STATUS_REFRESH_ENABLED=0' "$OUT_DIR/llm-access.service"
grep -F 'Environment=LLM_ACCESS_USAGE_JOURNAL_DIR=/var/lib/staticflow/llm-access/usage-journal' "$OUT_DIR/llm-access.service"
assert_absent '--sqlite-control' "$OUT_DIR/llm-access.service"
assert_absent '--duckdb-active-dir ${LLM_ACCESS_DUCKDB_ACTIVE_DIR}' "$OUT_DIR/llm-access.service"
assert_absent 'Environment=LLM_ACCESS_DUCKDB_ACTIVE_DIR=/var/lib/staticflow/llm-access/analytics-active' "$OUT_DIR/llm-access.service"
grep -F 'Environment=GEOIP_DB_PATH=/var/lib/staticflow/llm-access/geoip/GeoLite2-City.mmdb' "$OUT_DIR/llm-access.service"
assert_absent 'GEOIP_DB_PATH=/mnt/llm-access' "$OUT_DIR/llm-access.service"
grep -F 'MemoryHigh=3584M' "$OUT_DIR/llm-access.service"
grep -F 'MemoryMax=4096M' "$OUT_DIR/llm-access.service"
grep -F 'MemorySwapMax=1024M' "$OUT_DIR/llm-access.service"
assert_absent 'ReadWritePaths=' "$OUT_DIR/llm-access.service"
assert_absent 'ProtectSystem=' "$OUT_DIR/llm-access.service"
assert_absent 'PrivateTmp=' "$OUT_DIR/llm-access.service"
grep -F 'ExecStart=/usr/bin/bash -lc' "$OUT_DIR/llm-access-usage-worker.service"
grep -F "ExecStartPre=/usr/bin/bash -lc 'set -a; . /mnt/llm-access/config/neon.env; exec /usr/local/bin/staticflow-wait-llm-access-state analytics'" "$OUT_DIR/llm-access-usage-worker.service"
grep -F "ExecStart=/usr/bin/bash -lc 'set -a; . /mnt/llm-access/config/neon.env; exec /usr/local/bin/llm-access-usage-worker serve --bind 127.0.0.1:19081 --state-root /mnt/llm-access-usage --postgres-control-database-url-env LLM_ACCESS_CONTROL_DATABASE_URL --usage-journal-dir /var/lib/staticflow/llm-access/usage-journal --duckdb-active-dir /var/lib/staticflow/llm-access/analytics-active --duckdb-archive-dir /mnt/llm-access-usage/analytics/segments --duckdb-rollover-bytes 67108864 --usage-details-dir /mnt/llm-access-usage/details --request-cache-url-env LLM_ACCESS_REQUEST_CACHE_URL --request-cache-key-prefix llma'" "$OUT_DIR/llm-access-usage-worker.service"
grep -F -- '--bind 127.0.0.1:19081' "$OUT_DIR/llm-access-usage-worker.service"
grep -F -- '--postgres-control-database-url-env LLM_ACCESS_CONTROL_DATABASE_URL' "$OUT_DIR/llm-access-usage-worker.service"
grep -F -- '--request-cache-url-env LLM_ACCESS_REQUEST_CACHE_URL' "$OUT_DIR/llm-access-usage-worker.service"
grep -F -- '--request-cache-key-prefix llma' "$OUT_DIR/llm-access-usage-worker.service"
grep -F -- '--duckdb-active-dir /var/lib/staticflow/llm-access/analytics-active' "$OUT_DIR/llm-access-usage-worker.service"
grep -F -- '--duckdb-archive-dir /mnt/llm-access-usage/analytics/segments' "$OUT_DIR/llm-access-usage-worker.service"
grep -F -- '--usage-details-dir /mnt/llm-access-usage/details' "$OUT_DIR/llm-access-usage-worker.service"
grep -F -- '--usage-journal-dir /var/lib/staticflow/llm-access/usage-journal' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent '--duckdb ${LLM_ACCESS_DUCKDB}' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent '--usage-details-object-store-url' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent '--sqlite-control' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent '--duckdb-catalog-dir' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'Environment=STATICFLOW_LOG_SERVICE=llm-access-usage-worker' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'Environment=mimalloc_allow_thp=0' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'Environment=mimalloc_disallow_arena_alloc=1' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'Environment=mimalloc_purge_delay=0' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'Environment=LLM_ACCESS_STATE_ROOT=/mnt/llm-access-usage' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent 'Environment=LLM_ACCESS_SQLITE_CONTROL=' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'Environment=LLM_ACCESS_DUCKDB_ACTIVE_DIR=/var/lib/staticflow/llm-access/analytics-active' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent 'Environment=LLM_ACCESS_USAGE_JOURNAL_DIR=' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent 'Environment=LLM_ACCESS_DUCKDB_ARCHIVE_DIR=' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent 'Environment=LLM_ACCESS_USAGE_DETAILS_DIR=' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent 'Environment=LLM_ACCESS_DUCKDB_ROLLOVER_BYTES=' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'WorkingDirectory=/mnt/llm-access-usage' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'MemoryHigh=2200M' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'MemoryMax=3072M' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'MemorySwapMax=1024M' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'TasksMax=128' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent 'ReadWritePaths=' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent 'ProtectSystem=' "$OUT_DIR/llm-access-usage-worker.service"
assert_absent 'PrivateTmp=' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'MemoryHigh=1800M' "$OUT_DIR/juicefs-llm-access.resource-guard.conf"
grep -F 'MemoryMax=2560M' "$OUT_DIR/juicefs-llm-access.resource-guard.conf"
grep -F 'MemorySwapMax=0' "$OUT_DIR/juicefs-llm-access.resource-guard.conf"
grep -F 'cache-size=40960' "$OUT_DIR/mnt-llm\\x2daccess.mount"
grep -F 'Requires=juicefs-llm-access.service' "$OUT_DIR/juicefs-llm-access-usage.service"
grep -F 'ExecStartPre=/usr/bin/mkdir -p /mnt/llm-access/llm-access-usage' "$OUT_DIR/juicefs-llm-access-usage.service"
grep -F 'ExecStart=/home/ts_user/.local/bin/juicefs mount --cache-dir /var/cache/juicefs/llm-access-usage --cache-size 40960 --log /var/log/juicefs/llm-access-usage.log --no-syslog --no-usage-report --writeback --subdir /llm-access-usage ${JUICEFS_META_URL} /mnt/llm-access-usage' "$OUT_DIR/juicefs-llm-access-usage.service"
grep -F 'ExecStartPost=/usr/local/bin/staticflow-wait-llm-access-state mount-only' "$OUT_DIR/juicefs-llm-access-usage.service"
grep -F 'RequiresMountsFor=/mnt/llm-access' "$OUT_DIR/llm-access.service"
grep -F 'Requires=juicefs-llm-access.service juicefs-llm-access-usage.service' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'Environment=STATICFLOW_LOG_DIR=/var/log/staticflow-runtime' "$OUT_DIR/llm-access.service"
grep -F 'Environment=STATICFLOW_LOG_SERVICE=llm-access' "$OUT_DIR/llm-access.service"
grep -F 'Environment=mimalloc_generic_collect=1000' "$OUT_DIR/llm-access.service"
grep -F 'Environment=mimalloc_generic_collect=1000' "$OUT_DIR/llm-access-usage-worker.service"
grep -F 'mountpoint -q "$mount_point"' "$OUT_DIR/staticflow-wait-llm-access-state"
grep -F 'control_database_url="${LLM_ACCESS_CONTROL_DATABASE_URL:-}"' "$OUT_DIR/staticflow-wait-llm-access-state"
grep -F 'mode="mount-only"' "$OUT_DIR/staticflow-wait-llm-access-state"
grep -F 'mode" == "api"' "$OUT_DIR/staticflow-wait-llm-access-state"
grep -F 'mode" == "analytics"' "$OUT_DIR/staticflow-wait-llm-access-state"
grep -F '@llm_access path /v1/* /cc/v1/* /api/llm-gateway/* /api/kiro-gateway/* /api/codex-gateway/* /api/llm-access/*' "$OUT_DIR/Caddyfile"
grep -F 'handle @llm_access' "$OUT_DIR/Caddyfile"
grep -F 'reverse_proxy 127.0.0.1:19080' "$OUT_DIR/Caddyfile"
grep -F 'reverse_proxy 127.0.0.1:39080' "$OUT_DIR/Caddyfile"
